FROM openjdk:8u292-jdk-oracle as builder
WORKDIR application
ARG JAR_FILE=target/jetlinks-standalone.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM openjdk:8u292-jdk-oracle
WORKDIR application
COPY --from=builder application/dependencies/ ./
RUN true
COPY --from=builder application/snapshot-dependencies/ ./
RUN true
COPY --from=builder application/spring-boot-loader/ ./
RUN true
COPY --from=builder application/application/ ./
RUN true
COPY docker-entrypoint.sh ./
RUN true
RUN chmod +x docker-entrypoint.sh
RUN true
ENTRYPOINT ["./docker-entrypoint.sh"]